### ISSUE TITLE
Name for package

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/data.log#1]
Current name is `datalog`, which covers its purpose.

Unfortunately, there is also a query language with the [same name￼](￼￼https://en.wikipedia.org/wiki/Datalog).

Some other options
- `datalogger`
- `logdata`
- `datadiff` (doesn't cover it)
- `validate.log` (too restrictive I think)
- ...?

**Comment by edwindj** [comment]
data.log?

**Comment by markvanderloo** [comment]
:+1:

**Comment by markvanderloo** [comment]
Let's consider this one closed :-)
